[settings]
idiomatic_version_file_enable_tools = []

[tools]
node = "lts"
go = "1"
fzf = "latest"
#ag = "latest"
amazon-ecr-credential-helper = "latest"
argocd = "latest"
aws-cli = "latest"
aws-iam-authenticator = "latest"
azure-kubelogin = "latest"
bazelisk = "latest"
claude = "latest"
neovim = "latest"
docker-cli = "latest"
docker-compose = "latest"
evans = "latest"
fd = "latest"
gcloud = "latest"
github-cli = "latest"
helm = "latest"
jq = "latest"
jwt = "latest"
kafkactl = "latest"
kubectl = "latest"
pnpm = "latest"
postgres = "latest"
regctl = "latest"
regsync = "latest"
ripgrep = "latest"
starship = "latest"
rust = "latest"
temporal = "latest"
terraform = "latest"
1password = "latest"
bun = "latest"
